# Generated by Django 3.1.3 on 2020-11-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='state',
        ),
    ]
