# Generated by Django 3.1.3 on 2020-11-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerModel',
        ),
    ]
