# Generated by Django 3.1.2 on 2020-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201116_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
