# Generated by Django 3.1.3 on 2020-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delivery_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('publish_date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
    ]
