# Generated by Django 3.1.2 on 2020-12-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delivery_trxid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='trxId',
        ),
    ]
