# Generated by Django 3.1.4 on 2020-12-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_blog'),
        ('store', '0015_delivery_trxid'),
    ]

    operations = [
    ]
